#
# -------------------------------------------
# SERVER CONFIGURATION
# -------------------------------------------
#
server:
  port: 8403
#
# -------------------------------------------
# APPLICATION CONFIGURATION
# -------------------------------------------
#
spring:
  http:
    encoding:
      force: true
  redis:
    host: 10.136.28.102
    port: 6379
    password: 1qaz!QAZ
    database: 1
    timeout: 1000
    jedis:
      pool:
        max-idle: 10
        max-wait: -1
        min-idle: 0
        max-active: 200
syk:
  apple:
    store:
      storeUrl: https://reserve-prime.apple.com/CN/zh_CN/reserve/G/stores.json
      availabilityUrl: https://reserve-prime.apple.com/CN/zh_CN/reserve/G/availability.json
      cron: 0/10 * * * * ?
  alarm:
    monitor:
      item:
        - Pro Max 128GB 银色
        - Pro Max 256GB 银色
        - Pro Max 512GB 银色
      address: 苏州,上海,无锡
      tokenUrl: https://oapi.dingtalk.com/gettoken
      messageUrl: https://oapi.dingtalk.com/chat/send
      appKey: ding********
      appsecret: dZLVv**********
      chatId: chatac***********
      allChatId: cha**************
      allAlarm: false
farelog:
  name: monitor
  path: ./logs
  history-days: 10
logging:
  level:
    root: info
    com: debug
  size: 500